version = "0.1.0"

[site]
title = "Oli's site"
description = "Personal website of Oli McInnes"
url = "https://oli.mcinnes.cc"

[site.params]
disable_post_glyphs = true

[[site.params.side_links]]
label = "CV"
url = "/cv"

[site.params.side_links.icon_morph]
from = "h00,h11,h02,h12,v00,v01,v10,v21,d10a"
to = "h00,h10,h02,h12,v00,v01,v20,v21,d10a"
duration_ms = 250
fade_ms = 72
outline_width = 0
decorative = true

[[site.params.side_links]]
label = "Bio"
url = "/bio"

[site.params.side_links.icon_morph]
from = "h00,h10,h02,h12,v00,v01,v20,v21,d10a,d10b,d01a,d01b"
to = "h00,h10,h02,h12,v00,v01,v20,v21,d00a,d00b,d11a,d11b"
duration_ms = 250
fade_ms = 72
outline_width = 0
decorative = true

[[site.params.side_links]]
label = "Email"
url = "mailto:oli@mcinnes.cc"

[site.params.side_links.icon_morph]
from = "h00,h10,h01,h11,v00,v01,v20,d01b"
to = "h00,h10,h01,h11,v00,v20,v21,d11a"
duration_ms = 250
fade_ms = 72
outline_width = 0
decorative = true

[[site.params.side_links]]
label = "GitHub"
url = "https://github.com/olimci"

[site.params.side_links.icon_morph]
from = "h12,d00a,d01b"
to = "d00a,d10a,d01b,d11b"
duration_ms = 250
fade_ms = 72
outline_width = 0
decorative = true

[build]
minify = true

[content.defaults]
template = "post"
section = "page"

[content.markdown]
wikilinks = true
goldmark = { extensions = ["gfm", "table", "strikethrough", "tasklist", "deflist", "footnotes", "typographer"], parser = {auto_heading_id=true, attribute = true}, renderer = {hardbreaks = true} }

[content.git]
enabled = true
backfill = true

[redirects]
output = "_redirects"
shorten = "q"

redirects.entries = [{ from = "https://mcinnes.cc/*", to = "https://oli.mcinnes.cc/:splat", status = 301 },{ from = "http://mcinnes.cc/*", to = "https://oli.mcinnes.cc/:splat", status = 301 }, { from = "https://site-1oc.pages.dev/*", to = "https://oli.mcinnes.cc/:splat", status = 301 }, { from = "http://site-1oc.pages.dev/*", to = "https://oli.mcinnes.cc/:splat", status = 301 }]

[rss]
output = "rss.xml"
sections = ["posts"]
limit = 50
include_drafts = false

[sitemap]
output = "sitemap.xml"
include_drafts = false
