version = "0.1.0"

[site]
title = "Oli's site"
description = "Personal website of Oli McInnes"
url = "https://oli.mcinnes.cc"

[site.params]
disable_post_glyphs = true
nav_title = "olimci"

[build]
minify = true

[content.defaults]
template = "post"
section = "page"

[content.markdown]
wikilinks = true
goldmark = { extensions = ["gfm", "table", "strikethrough", "tasklist", "deflist", "footnotes", "typographer"], parser = {auto_heading_id=true, attribute = true}, renderer = {hardbreaks = true} }

[content.git]
enabled = true
backfill = true

[redirects]
output = "_redirects"
disable_short_links = true

[rss]
output = "rss.xml"
sections = ["posts"]
limit = 50
include_drafts = false

[sitemap]
output = "sitemap.xml"
include_drafts = false
