title = "Links"
description = "Personal links and contact details"
template = "links"
section = "pages"

[[params.exported_links]]
label = "CV"
url = "/cv"
icon = "briefcase"

[[params.exported_links]]
label = "Email"
url = "mailto:oli@mcinnes.cc"
icon = "email"

[[params.exported_links]]
label = "GitHub"
url = "https://github.com/olimci"
icon = "script_code"

[[params.unexported_links]]
label = "Instagram"
url = "https://www.instagram.com/mcinnesoliver/"
icon = "camera"

[sitemap]
include = true
changefreq = "monthly"
priority = 0.8

[rss]
include = false
